CREATE TABLE `minions`(
`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
`age` INT NOT NULL,
PRIMARY KEY (`id`));

CREATE TABLE `towns`(
`town_id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50),
PRIMARY KEY (`town_id`));